# Generated by Django 5.1.2 on 2024-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_user_alter_customer_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
